"""payees

Revision ID: 19dfd2d0db91
Revises: 5a1ea0f79269
Create Date: 2026-06-11 13:37:49.531504

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19dfd2d0db91'
down_revision: Union[str, Sequence[str], None] = '5a1ea0f79269'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payees',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payees_user_id'), 'payees', ['user_id'], unique=False)
    op.create_index('uq_payees_user_lower_name', 'payees', ['user_id', sa.literal_column('lower(name)')], unique=True)
    op.add_column('transactions', sa.Column('payee_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_transactions_payee_id'), 'transactions', ['payee_id'], unique=False)
    op.create_foreign_key('fk_transactions_payee_id', 'transactions', 'payees', ['payee_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_transactions_payee_id', 'transactions', type_='foreignkey')
    op.drop_index(op.f('ix_transactions_payee_id'), table_name='transactions')
    op.drop_column('transactions', 'payee_id')
    op.drop_index('uq_payees_user_lower_name', table_name='payees')
    op.drop_index(op.f('ix_payees_user_id'), table_name='payees')
    op.drop_table('payees')
    # ### end Alembic commands ###
